# Основное Окно
window_logo = "src\\general\\logo.ico"
width = 502
height = 932

# Заготовки для шрифтов и цветов
global_font = ("Aptos", "12", "bold")
label_font = ("Aptos", "20", "bold")
fg_w = "white"
fg_b = "black"
bg_w = "white"

# Изображения
solid_bg = "src\\general\\bg_2.png"
bg_with_logo = "src\\general\\bg_start.png"
button_start = "src\\general\\b_start.png"
button_start_light = "src\\general\\b_start_light.png"
button_start_dark = "src\\general\\b_start_dark.png"
arrows_block_bg = "src\\general\\bg_arrows.png"
arrow_back = "src\\general\\back.png"
arrow_back_dark = "src\\general\\back_dark.png"
arrow_back_light = "src\\general\\back_light.png"
arrow_forward = "src\\general\\forward.png"
arrow_forward_dark = "src\\general\\forward_dark.png"
arrow_forward_light = "src\\general\\forward_light.png"

# Второе окно
logo_2 = "src\\general\\logo_2.png"
date_button = "src\\win2\\b_2.png"
date_button_dark = "src\\win2\\b_2_dark.png"
date_button_light = "src\\win2\\b_2_light.png"
date_button_on = "src\\win2\\b_2_border_white.png"  # rename file border -> on
date_button_gray = "src\\win2\\b_2_gray.png"
counter_bg = "src\\win2\\bg_counter.png"
minus_normal = "src\\win2\\minus.png"
minus_light = "src\\win2\\minus_light.png"
minus_dark = "src\\win2\\minus_dark.png"
plus_normal = "src\\win2\\plus.png"
plus_light = "src\\win2\\plus_light.png"
plus_dark = "src\\win2\\plus_dark.png"

# Третье окно
dd_button = "src\\win3\\dish_or_drinks.png"
dd_button_white = "src\\win3\\dish_or_drinks_white.png"
dd_button_dark = "src\\win3\\dish_or_drinks_dark.png"
fd_button = "src\\win3\\food_or_drinks.png"
fd_button_light = "src\\win3\\food_or_drinks_light.png"
fd_button_dark = "src\\win3\\food_or_drinks_dark.png"
card1 = "src\\win3\\card_1.png"
card2 = "src\\win3\\card_2.png"
card3 = "src\\win3\\card_3.png"
card4 = "src\\win3\\card_4.png"
card5 = "src\\win3\\card_5.png"
card6 = "src\\win3\\card_6.png"
card7 = "src\\win3\\card_7.png"
card8 = "src\\win3\\card_8.png"
cardn1 = "src\\win3\\card_n1.png"
cardn2 = "src\\win3\\card_n2.png"
cardn3 = "src\\win3\\card_n3.png"
cardn4 = "src\\win3\\card_n4.png"
cardn5 = "src\\win3\\card_n5.png"
cardn6 = "src\\win3\\card_n6.png"
number = "src\\win3\\number.png"
number_light = "src\\win3\\number_light.png"
number_dark = "src\\win3\\number_dark.png"
number_light_dark = "src\\win3\\number_light_dark.png"
buy = "src\\win3\\buy.png"
buy_dark = "src\\win3\\buy_dark.png"
buy_light = "src\\win3\\buy_light.png"
bg_counter_food = "src\\win3\\bg_counter_food.png"
food_minus_normal = "src\\win3\\food_minus.png"
food_minus_light = "src\\win3\\food_minus_light.png"
food_minus_dark = "src\\win3\\food_minus_dark.png"
food_plus_normal = "src\\win3\\food_plus.png"
food_plus_light = "src\\win3\\food_plus_light.png"
food_plus_dark = "src\\win3\\food_plus_dark.png"
check = "src\\win3\\check.png"
check_dark = "src\\win3\\check_dark.png"
check_light = "src\\win3\\check_light.png"
